# Generated by Django 5.0 on 2023-12-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavbarSections',
            new_name='NavbarSection',
        ),
    ]
