# Generated by Django 5.0 on 2023-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_product_delete_navbarsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
